// ============================================
// MOCK DATA FOR PESANTREN ADMIN PANEL
// ============================================

import type { 
  User, 
  Santri, 
  Payment, 
  BlogPost, 
  DashboardStats, 
  ChartData, 
  RecentActivity,
  Category,
  Tag,
  TenagaPengajar,
  BankAccount
} from '@/types';

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalStudents: 1247,
  paymentsVerified: 892,
  pendingRegistrations: 156,
  blogPosts: 48,
  activeTeachers: 86,
  totalRevenue: 1250000000,
};

// Monthly Registration Chart Data
export const monthlyRegistrationData: ChartData[] = [
  { name: 'Jan', value: 45 },
  { name: 'Feb', value: 52 },
  { name: 'Mar', value: 78 },
  { name: 'Apr', value: 120 },
  { name: 'May', value: 145 },
  { name: 'Jun', value: 189 },
  { name: 'Jul', value: 167 },
  { name: 'Aug', value: 134 },
  { name: 'Sep', value: 98 },
  { name: 'Oct', value: 76 },
  { name: 'Nov', value: 65 },
  { name: 'Dec', value: 78 },
];

// Revenue Chart Data
export const revenueData: ChartData[] = [
  { name: 'Jan', value: 85000000 },
  { name: 'Feb', value: 92000000 },
  { name: 'Mar', value: 125000000 },
  { name: 'Apr', value: 180000000 },
  { name: 'May', value: 195000000 },
  { name: 'Jun', value: 210000000 },
  { name: 'Jul', value: 178000000 },
  { name: 'Aug', value: 156000000 },
  { name: 'Sep', value: 120000000 },
  { name: 'Oct', value: 98000000 },
  { name: 'Nov', value: 88000000 },
  { name: 'Dec', value: 95000000 },
];

// Status Distribution
export const statusDistribution: ChartData[] = [
  { name: 'Diterima', value: 892 },
  { name: 'Terverifikasi', value: 156 },
  { name: 'Pending', value: 134 },
  { name: 'Ditolak', value: 65 },
];

// Recent Activities
export const recentActivities: RecentActivity[] = [
  {
    id: '1',
    type: 'registration',
    title: 'Pendaftaran Baru',
    description: 'Ahmad Fauzi mendaftar sebagai santri baru',
    timestamp: '2026-02-07T08:30:00Z',
    user: 'Ahmad Fauzi',
  },
  {
    id: '2',
    type: 'payment',
    title: 'Pembayaran Diverifikasi',
    description: 'Pembayaran Siti Aisyah telah diverifikasi',
    timestamp: '2026-02-07T08:15:00Z',
    user: 'Admin',
  },
  {
    id: '3',
    type: 'post',
    title: 'Artikel Dipublikasi',
    description: 'Artikel "Keutamaan Menuntut Ilmu" telah dipublikasi',
    timestamp: '2026-02-07T07:45:00Z',
    user: 'Ustadz Ibrahim',
  },
  {
    id: '4',
    type: 'announcement',
    title: 'Pengumuman Baru',
    description: 'Jadwal Ujian Semester Genap 2026',
    timestamp: '2026-02-07T07:30:00Z',
    user: 'Admin',
  },
  {
    id: '5',
    type: 'registration',
    title: 'Status Diperbarui',
    description: 'Muhammad Rizky diterima sebagai santri',
    timestamp: '2026-02-07T07:00:00Z',
    user: 'Panitia PSB',
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    username: 'admin',
    email: 'admin@pesantren.sch.id',
    first_name: 'Super',
    last_name: 'Admin',
    phone: '081234567890',
    avatar: undefined,
    role: 'admin',
    is_active: true,
    is_staff: true,
    is_superuser: true,
    date_joined: '2024-01-01T00:00:00Z',
    last_login: '2026-02-07T08:00:00Z',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    username: 'ustadz.ibrahim',
    email: 'ibrahim@pesantren.sch.id',
    first_name: 'Ibrahim',
    last_name: 'Al-Farisi',
    phone: '081234567891',
    avatar: undefined,
    role: 'teacher',
    is_active: true,
    is_staff: true,
    is_superuser: false,
    date_joined: '2024-03-15T00:00:00Z',
    last_login: '2026-02-06T14:30:00Z',
    created_at: '2024-03-15T00:00:00Z',
  },
  {
    id: '3',
    username: 'operator.psb',
    email: 'psb@pesantren.sch.id',
    first_name: 'Fatimah',
    last_name: 'Azzahra',
    phone: '081234567892',
    avatar: undefined,
    role: 'operator',
    is_active: true,
    is_staff: true,
    is_superuser: false,
    date_joined: '2024-06-01T00:00:00Z',
    last_login: '2026-02-07T07:45:00Z',
    created_at: '2024-06-01T00:00:00Z',
  },
];

// Mock Santri (Students)
export const mockSantri: Santri[] = [
  {
    id: '1',
    nama_lengkap: 'Ahmad Fauzi bin Abdullah',
    nama_panggilan: 'Fauzi',
    nisn: '0012345678',
    tempat_lahir: 'Jakarta',
    tanggal_lahir: '2010-05-15',
    jenis_kelamin: 'L',
    agama: 'Islam',
    kewarganegaraan: 'WNI',
    anak_ke: 2,
    jumlah_saudara: 3,
    bahasa_sehari_hari: 'Indonesia',
    golongan_darah: 'O',
    tinggi_badan: 155,
    berat_badan: 45,
    riwayat_penyakit: '-',
    tinggal_dengan: 'Orang Tua',
    nama_ayah: 'Abdullah bin Ahmad',
    nik_ayah: '3201234567890001',
    tempat_lahir_ayah: 'Bogor',
    tanggal_lahir_ayah: '1980-03-20',
    agama_ayah: 'Islam',
    kewarganegaraan_ayah: 'WNI',
    pendidikan_ayah: 'S1',
    pekerjaan_ayah: 'Wiraswasta',
    no_hp_ayah: '081234567890',
    status_ayah: 'Hidup',
    nama_ibu: 'Aisyah binti Umar',
    nik_ibu: '3201234567890002',
    tempat_lahir_ibu: 'Depok',
    tanggal_lahir_ibu: '1985-07-10',
    agama_ibu: 'Islam',
    kewarganegaraan_ibu: 'WNI',
    pendidikan_ibu: 'S1',
    pekerjaan_ibu: 'Guru',
    no_hp_ibu: '081234567891',
    status_ibu: 'Hidup',
    alamat_orangtua: 'Jl. Mawar No. 123, RT 01/RW 02',
    alamat: 'Jl. Mawar No. 123, RT 01/RW 02',
    desa: 'Sukamaju',
    kecamatan: 'Cimanggis',
    kabupaten: 'Depok',
    provinsi: 'Jawa Barat',
    kode_pos: '16451',
    no_hp: '081234567892',
    email: 'fauzi@gmail.com',
    asal_sekolah: 'SDN 01 Sukamaju',
    npsn_sekolah: '20228817',
    kelas_terakhir: '6',
    tahun_lulus: '2024',
    no_ijazah: 'DN-01 Dd 0012345',
    kelas_diterima: '7A',
    tanggal_diterima: '2024-07-15',
    status: 'accepted',
    catatan: 'Santri berprestasi',
    foto_santri: undefined,
    foto_ktp: undefined,
    foto_akta: undefined,
    foto_ijazah: undefined,
    surat_sehat: undefined,
    foto_santri_approved: true,
    foto_ktp_approved: true,
    foto_akta_approved: true,
    foto_ijazah_approved: true,
    surat_sehat_approved: true,
    created_at: '2024-07-01T10:00:00Z',
    updated_at: '2024-07-15T14:00:00Z',
  },
  {
    id: '2',
    nama_lengkap: 'Siti Aisyah binti Rahman',
    nama_panggilan: 'Aisyah',
    nisn: '0012345679',
    tempat_lahir: 'Bandung',
    tanggal_lahir: '2010-08-22',
    jenis_kelamin: 'P',
    agama: 'Islam',
    kewarganegaraan: 'WNI',
    anak_ke: 1,
    jumlah_saudara: 2,
    bahasa_sehari_hari: 'Indonesia',
    golongan_darah: 'A',
    tinggi_badan: 150,
    berat_badan: 42,
    riwayat_penyakit: '-',
    tinggal_dengan: 'Orang Tua',
    nama_ayah: 'Rahman bin Salim',
    nik_ayah: '3201234567890003',
    tempat_lahir_ayah: 'Bandung',
    tanggal_lahir_ayah: '1978-11-05',
    agama_ayah: 'Islam',
    kewarganegaraan_ayah: 'WNI',
    pendidikan_ayah: 'S2',
    pekerjaan_ayah: 'Dosen',
    no_hp_ayah: '081234567893',
    status_ayah: 'Hidup',
    nama_ibu: 'Khadijah binti Ali',
    nik_ibu: '3201234567890004',
    tempat_lahir_ibu: 'Cimahi',
    tanggal_lahir_ibu: '1982-04-18',
    agama_ibu: 'Islam',
    kewarganegaraan_ibu: 'WNI',
    pendidikan_ibu: 'S1',
    pekerjaan_ibu: 'Dokter',
    no_hp_ibu: '081234567894',
    status_ibu: 'Hidup',
    alamat_orangtua: 'Jl. Melati No. 45, RT 03/RW 05',
    alamat: 'Jl. Melati No. 45, RT 03/RW 05',
    desa: 'Sukajadi',
    kecamatan: 'Sukajadi',
    kabupaten: 'Bandung',
    provinsi: 'Jawa Barat',
    kode_pos: '40162',
    no_hp: '081234567895',
    email: 'aisyah@gmail.com',
    asal_sekolah: 'SDIT Al-Hikmah',
    npsn_sekolah: '20229918',
    kelas_terakhir: '6',
    tahun_lulus: '2024',
    no_ijazah: 'DN-01 Dd 0012346',
    status: 'verified',
    catatan: 'Menunggu hasil tes',
    foto_santri: undefined,
    foto_ktp: undefined,
    foto_akta: undefined,
    foto_ijazah: undefined,
    surat_sehat: undefined,
    foto_santri_approved: true,
    foto_ktp_approved: true,
    foto_akta_approved: false,
    foto_ijazah_approved: true,
    surat_sehat_approved: false,
    created_at: '2024-07-05T09:30:00Z',
    updated_at: '2024-07-10T11:00:00Z',
  },
  {
    id: '3',
    nama_lengkap: 'Muhammad Rizky Pratama',
    nama_panggilan: 'Rizky',
    nisn: '0012345680',
    tempat_lahir: 'Surabaya',
    tanggal_lahir: '2010-12-01',
    jenis_kelamin: 'L',
    agama: 'Islam',
    kewarganegaraan: 'WNI',
    anak_ke: 3,
    jumlah_saudara: 4,
    bahasa_sehari_hari: 'Indonesia',
    golongan_darah: 'B',
    tinggi_badan: 158,
    berat_badan: 48,
    riwayat_penyakit: 'Asma ringan',
    tinggal_dengan: 'Orang Tua',
    nama_ayah: 'Pratama Wijaya',
    nik_ayah: '3201234567890005',
    tempat_lahir_ayah: 'Surabaya',
    tanggal_lahir_ayah: '1975-06-15',
    agama_ayah: 'Islam',
    kewarganegaraan_ayah: 'WNI',
    pendidikan_ayah: 'S1',
    pekerjaan_ayah: 'Pengusaha',
    no_hp_ayah: '081234567896',
    status_ayah: 'Hidup',
    nama_ibu: 'Nur Hidayah',
    nik_ibu: '3201234567890006',
    tempat_lahir_ibu: 'Malang',
    tanggal_lahir_ibu: '1980-09-25',
    agama_ibu: 'Islam',
    kewarganegaraan_ibu: 'WNI',
    pendidikan_ibu: 'D3',
    pekerjaan_ibu: 'Ibu Rumah Tangga',
    no_hp_ibu: '081234567897',
    status_ibu: 'Hidup',
    alamat_orangtua: 'Jl. Kenanga No. 78, RT 02/RW 01',
    alamat: 'Jl. Kenanga No. 78, RT 02/RW 01',
    desa: 'Wonokromo',
    kecamatan: 'Wonokromo',
    kabupaten: 'Surabaya',
    provinsi: 'Jawa Timur',
    kode_pos: '60243',
    no_hp: '081234567898',
    email: 'rizky@gmail.com',
    asal_sekolah: 'SD Muhammadiyah 1 Surabaya',
    npsn_sekolah: '20531019',
    kelas_terakhir: '6',
    tahun_lulus: '2024',
    no_ijazah: 'DN-01 Dd 0012347',
    status: 'pending',
    catatan: 'Dokumen belum lengkap',
    foto_santri: undefined,
    foto_ktp: undefined,
    foto_akta: undefined,
    foto_ijazah: undefined,
    surat_sehat: undefined,
    foto_santri_approved: true,
    foto_ktp_approved: false,
    foto_akta_approved: false,
    foto_ijazah_approved: false,
    surat_sehat_approved: false,
    created_at: '2024-07-08T14:00:00Z',
    updated_at: '2024-07-08T14:00:00Z',
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  { id: '1', name: 'Kegiatan', slug: 'kegiatan', order: 1, created_at: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'Pendidikan', slug: 'pendidikan', order: 2, created_at: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Prestasi', slug: 'prestasi', order: 3, created_at: '2024-01-01T00:00:00Z' },
  { id: '4', name: 'Pengumuman', slug: 'pengumuman', order: 4, created_at: '2024-01-01T00:00:00Z' },
];

// Mock Tags
export const mockTags: Tag[] = [
  { id: '1', name: 'Ramadhan', slug: 'ramadhan', order: 1, created_at: '2024-01-01T00:00:00Z' },
  { id: '2', name: 'Tahfidz', slug: 'tahfidz', order: 2, created_at: '2024-01-01T00:00:00Z' },
  { id: '3', name: 'Olahraga', slug: 'olahraga', order: 3, created_at: '2024-01-01T00:00:00Z' },
  { id: '4', name: 'Lomba', slug: 'lomba', order: 4, created_at: '2024-01-01T00:00:00Z' },
];

// Mock Blog Posts
export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Keutamaan Menuntut Ilmu dalam Islam',
    slug: 'keutamaan-menuntut-ilmu-dalam-islam',
    content: '<p>Menuntut ilmu adalah kewajiban bagi setiap muslim...</p>',
    excerpt: 'Menuntut ilmu adalah kewajiban bagi setiap muslim. Rasulullah SAW bersabda...',
    featured_image: undefined,
    author_id: '2',
    category_id: '2',
    meta_title: 'Keutamaan Menuntut Ilmu dalam Islam',
    meta_description: 'Artikel tentang keutamaan menuntut ilmu dalam Islam',
    meta_keywords: 'ilmu, islam, pendidikan',
    status: 'published',
    is_featured: true,
    published_at: '2024-06-15T10:00:00Z',
    views_count: 1250,
    likes_count: 89,
    shares_count: 34,
    created_at: '2024-06-15T09:00:00Z',
    updated_at: '2024-06-15T10:00:00Z',
  },
  {
    id: '2',
    title: 'Jadwal Penerimaan Santri Baru 2026',
    slug: 'jadwal-penerimaan-santri-baru-2026',
    content: '<p>Pendaftaran santri baru tahun ajaran 2026/2027 akan dibuka...</p>',
    excerpt: 'Pendaftaran santri baru tahun ajaran 2026/2027 akan dibuka pada tanggal...',
    featured_image: undefined,
    author_id: '1',
    category_id: '4',
    meta_title: 'Jadwal Penerimaan Santri Baru 2026',
    meta_description: 'Informasi jadwal penerimaan santri baru tahun 2026',
    meta_keywords: 'pendaftaran, santri baru, 2026',
    status: 'published',
    is_featured: false,
    published_at: '2024-07-01T08:00:00Z',
    views_count: 3450,
    likes_count: 156,
    shares_count: 89,
    created_at: '2024-06-30T14:00:00Z',
    updated_at: '2024-07-01T08:00:00Z',
  },
];

// Mock Teachers
export const mockTeachers: TenagaPengajar[] = [
  {
    id: '1',
    nama_lengkap: 'Ustadz Ibrahim Al-Farisi, Lc., M.A.',
    nama_panggilan: 'Ustadz Ibrahim',
    jenis_kelamin: 'L',
    tempat_lahir: 'Madinah',
    tanggal_lahir: '1985-03-15',
    alamat: 'Komplek Pesantren Blok A No. 1',
    no_hp: '081234567891',
    email: 'ibrahim@pesantren.sch.id',
    pendidikan_terakhir: 'S2',
    universitas: 'Universitas Islam Madinah',
    tahun_lulus: '2012',
    bidang_keahlian: 'Tafsir dan Hadits',
    mata_pelajaran: 'Al-Quran, Hadits, Tafsir',
    pengalaman_mengajar: '12 tahun',
    prestasi: 'Hafidz 30 Juz, Juara 1 MTQ Nasional',
    riwayat_pendidikan: 'S1 Universitas Al-Azhar, S2 Universitas Islam Madinah',
    organisasi: 'MUI, ICMI',
    karya_tulis: 'Tafsir Al-Muyassar',
    motto: 'Ilmu adalah cahaya',
    whatsapp: '081234567891',
    facebook: '',
    instagram: '@ustadz.ibrahim',
    twitter: '',
    linkedin: '',
    youtube: '',
    tiktok: '',
    order: 1,
    is_published: true,
    is_featured: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// Mock Bank Accounts
export const mockBankAccounts: BankAccount[] = [
  {
    id: '1',
    nama_bank: 'BSI',
    nama_bank_custom: 'Bank Syariah Indonesia',
    nomor_rekening: '7012345678',
    nama_pemilik_rekening: 'Yayasan Pondok Pesantren',
    biaya_pendaftaran: 2500000,
    is_active: true,
    keterangan: 'Rekening utama pendaftaran',
    order: 1,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: '1',
    santri_id: '1',
    bank_pengirim: 'BCA',
    no_rekening_pengirim: '1234567890',
    nama_pemilik_rekening: 'Abdullah bin Ahmad',
    rekening_tujuan: '7012345678',
    jumlah_transfer: 2500000,
    bukti_transfer: undefined,
    status: 'verified',
    catatan: 'Pembayaran lunas',
    verified_by_id: '1',
    verified_at: '2024-07-02T10:00:00Z',
    created_at: '2024-07-01T14:00:00Z',
    updated_at: '2024-07-02T10:00:00Z',
  },
  {
    id: '2',
    santri_id: '2',
    bank_pengirim: 'Mandiri',
    no_rekening_pengirim: '1234567891',
    nama_pemilik_rekening: 'Rahman bin Salim',
    rekening_tujuan: '7012345678',
    jumlah_transfer: 2500000,
    bukti_transfer: undefined,
    status: 'pending',
    created_at: '2024-07-06T09:00:00Z',
    updated_at: '2024-07-06T09:00:00Z',
  },
];

// Helper function to format currency
export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
};

// Helper function to format date
export const formatDate = (date: string): string => {
  return new Intl.DateTimeFormat('id-ID', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(new Date(date));
};

// Helper function to format datetime
export const formatDateTime = (date: string): string => {
  return new Intl.DateTimeFormat('id-ID', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(new Date(date));
};

// Helper function to get relative time
export const getRelativeTime = (date: string): string => {
  const now = new Date();
  const past = new Date(date);
  const diffInSeconds = Math.floor((now.getTime() - past.getTime()) / 1000);

  if (diffInSeconds < 60) return 'Baru saja';
  if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)} menit lalu`;
  if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)} jam lalu`;
  if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)} hari lalu`;
  return formatDate(date);
};
