import { z } from 'zod';
export const santriRegistrationSchema = z.object({
  namaLengkap: z.string().min(1),
  namaPanggilan: z.string().optional(),
  nisn: z.string().regex(/^\d{10}$/, 'NISN must be 10 digits'),
  tempatLahir: z.string().min(1),
  tanggalLahir: z.string().refine((date) => !isNaN(Date.parse(date)), {
    message: "Invalid date string",
  }),
  jenisKelamin: z.enum(['L', 'P']),
  agama: z.string().default('Islam'),
  kewarganegaraan: z.enum(['WNI', 'WNA']).default('WNI'),
  anakKe: z.number().int().optional(),
  jumlahSaudara: z.number().int().optional(),
  golonganDarah: z.enum(['A', 'B', 'AB', 'O']).optional(),
  tinggiBadan: z.number().int().optional(),
  beratBadan: z.number().int().optional(),
  riwayatPenyakit: z.string().optional(),
  tinggalDengan: z.enum(['Orang Tua', 'Wali', 'Lainnya']).optional(),
  bahasaSehariHari: z.string().optional(),
  namaAyah: z.string().min(1),
  namaIbu: z.string().min(1),
  nikAyah: z.string().length(16).optional(),
  nikIbu: z.string().length(16).optional(),
  pekerjaanAyah: z.string().optional(),
  pekerjaanIbu: z.string().optional(),
  pendidikanAyah: z.string().optional(),
  pendidikanIbu: z.string().optional(),
  noHpAyah: z.string().optional(),
  noHpIbu: z.string().optional(),
  penghasilanAyah: z.string().optional(),
  penghasilanIbu: z.string().optional(),
  alamatOrangTua: z.string().optional(),
  statusAyah: z.string().default('Hidup'),
  statusIbu: z.string().default('Hidup'),
  agamaAyah: z.string().optional(),
  agamaIbu: z.string().optional(),
  kewarganegaraanAyah: z.string().optional(),
  kewarganegaraanIbu: z.string().optional(),
  tempatLahirAyah: z.string().optional(),
  tempatLahirIbu: z.string().optional(),
  tanggalLahirAyah: z.string().optional(),
  tanggalLahirIbu: z.string().optional(),
  alamat: z.string().min(1),
  desa: z.string().optional(),
  kecamatan: z.string().optional(),
  kabupaten: z.string().optional(),
  provinsi: z.string().optional(),
  kodePos: z.string().optional(),
  noHp: z.string().min(1),
  email: z.string().email().optional(),
  asalSekolah: z.string().min(1),
  npsnSekolah: z.string().optional(),
  kelasTerakhir: z.string().min(1),
  tahunLulus: z.string().optional(),
  noIjazah: z.string().optional(),
  fotoSantri: z.string().optional(), 
  fotoKtp: z.string().optional(),
  fotoAkta: z.string().optional(),
  fotoIjazah: z.string().optional(),
  fotoKk: z.string().optional(),
  suratSehat: z.string().optional(),
  fotoSantriApproved: z.boolean().optional(),
  fotoKtpApproved: z.boolean().optional(),
  fotoAktaApproved: z.boolean().optional(),
  fotoIjazahApproved: z.boolean().optional(),
  fotoKkApproved: z.boolean().optional(),
  suratSehatApproved: z.boolean().optional(),
  status: z.enum(['pending', 'verified', 'accepted', 'rejected']).optional(),
  catatan: z.string().optional(),
});