import { z } from 'zod';
export const santriRegistrationSchema = z.object({
    namaLengkap: z.string().min(1),
    namaPanggilan: z.string().optional(),
    nisn: z.string().regex(/^\d{10}$/, 'NISN must be 10 digits'),
    tempatLahir: z.string().min(1),
    tanggalLahir: z.string().refine((date) => !isNaN(Date.parse(date)), {
        message: "Invalid date string",
    }),
    jenisKelamin: z.enum(['L', 'P']),
    agama: z.string().default('Islam'),
    kewarganegaraan: z.enum(['WNI', 'WNA']).default('WNI'),
    anakKe: z.number().int().optional(),
    jumlahSaudara: z.number().int().optional(),
    golonganDarah: z.enum(['A', 'B', 'AB', 'O']).optional().default('A'),
    tinggiBadan: z.number().int().optional(),
    beratBadan: z.number().int().optional(),
    riwayatPenyakit: z.string().optional().default('-'),
    tinggalDengan: z.enum(['Orang Tua', 'Wali', 'Lainnya']).optional().default('Orang Tua'),
    bahasaSehariHari: z.string().optional().default('Indonesia'),
    namaAyah: z.string().min(1),
    namaIbu: z.string().min(1),
    nikAyah: z.string().optional().default('-'),
    nikIbu: z.string().optional().default('-'),
    pekerjaanAyah: z.string().optional().default('-'),
    pekerjaanIbu: z.string().optional().default('-'),
    pendidikanAyah: z.string().optional().default('-'),
    pendidikanIbu: z.string().optional().default('-'),
    noHpAyah: z.string().optional().default('-'),
    noHpIbu: z.string().optional().default('-'),
    penghasilanAyah: z.string().optional().default('-'),
    penghasilanIbu: z.string().optional().default('-'),
    alamatOrangTua: z.string().optional().default('-'),
    statusAyah: z.string().default('Hidup'),
    statusIbu: z.string().default('Hidup'),
    agamaAyah: z.string().optional().default('Islam'),
    agamaIbu: z.string().optional().default('Islam'),
    kewarganegaraanAyah: z.string().optional().default('WNI'),
    kewarganegaraanIbu: z.string().optional().default('WNI'),
    tempatLahirAyah: z.string().optional().default('-'),
    tempatLahirIbu: z.string().optional().default('-'),
    tanggalLahirAyah: z.string().optional(),
    tanggalLahirIbu: z.string().optional(),
    alamat: z.string().min(1),
    desa: z.string().optional().default('-'),
    kecamatan: z.string().optional().default('-'),
    kabupaten: z.string().optional().default('-'),
    provinsi: z.string().optional().default('-'),
    kodePos: z.string().optional().default('-'),
    noHp: z.string().min(1),
    email: z.string().email().optional().or(z.literal('')),
    asalSekolah: z.string().min(1),
    npsnSekolah: z.string().optional().default('-'),
    kelasTerakhir: z.string().min(1),
    tahunLulus: z.string().optional().default('-'),
    noIjazah: z.string().optional().default('-'),
    fotoSantri: z.string().optional(),
    fotoKtp: z.string().optional(),
    fotoAkta: z.string().optional(),
    fotoIjazah: z.string().optional(),
    fotoKk: z.string().optional(),
    suratSehat: z.string().optional(),
    fotoSantriApproved: z.boolean().optional(),
    fotoKtpApproved: z.boolean().optional(),
    fotoAktaApproved: z.boolean().optional(),
    fotoIjazahApproved: z.boolean().optional(),
    fotoKkApproved: z.boolean().optional(),
    suratSehatApproved: z.boolean().optional(),
    status: z.enum(['pending', 'verified', 'accepted', 'rejected']).optional(),
    catatan: z.string().optional(),
});
