"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.santriRegistrationSchema = void 0;
const zod_1 = require("zod");
exports.santriRegistrationSchema = zod_1.z.object({
    namaLengkap: zod_1.z.string().min(1),
    namaPanggilan: zod_1.z.string().optional(),
    nisn: zod_1.z.string().regex(/^\d{10}$/, 'NISN must be 10 digits'),
    tempatLahir: zod_1.z.string().min(1),
    tanggalLahir: zod_1.z.string().refine((date) => !isNaN(Date.parse(date)), {
        message: "Invalid date string",
    }),
    jenisKelamin: zod_1.z.enum(['L', 'P']),
    agama: zod_1.z.string().default('Islam'),
    kewarganegaraan: zod_1.z.enum(['WNI', 'WNA']).default('WNI'),
    anakKe: zod_1.z.number().int().optional(),
    jumlahSaudara: zod_1.z.number().int().optional(),
    golonganDarah: zod_1.z.enum(['A', 'B', 'AB', 'O']).optional().default('A'),
    tinggiBadan: zod_1.z.number().int().optional(),
    beratBadan: zod_1.z.number().int().optional(),
    riwayatPenyakit: zod_1.z.string().optional().default('-'),
    tinggalDengan: zod_1.z.enum(['Orang Tua', 'Wali', 'Lainnya']).optional().default('Orang Tua'),
    bahasaSehariHari: zod_1.z.string().optional().default('Indonesia'),
    namaAyah: zod_1.z.string().min(1),
    namaIbu: zod_1.z.string().min(1),
    nikAyah: zod_1.z.string().optional().default('-'),
    nikIbu: zod_1.z.string().optional().default('-'),
    pekerjaanAyah: zod_1.z.string().optional().default('-'),
    pekerjaanIbu: zod_1.z.string().optional().default('-'),
    pendidikanAyah: zod_1.z.string().optional().default('-'),
    pendidikanIbu: zod_1.z.string().optional().default('-'),
    noHpAyah: zod_1.z.string().optional().default('-'),
    noHpIbu: zod_1.z.string().optional().default('-'),
    penghasilanAyah: zod_1.z.string().optional().default('-'),
    penghasilanIbu: zod_1.z.string().optional().default('-'),
    alamatOrangTua: zod_1.z.string().optional().default('-'),
    statusAyah: zod_1.z.string().default('Hidup'),
    statusIbu: zod_1.z.string().default('Hidup'),
    agamaAyah: zod_1.z.string().optional().default('Islam'),
    agamaIbu: zod_1.z.string().optional().default('Islam'),
    kewarganegaraanAyah: zod_1.z.string().optional().default('WNI'),
    kewarganegaraanIbu: zod_1.z.string().optional().default('WNI'),
    tempatLahirAyah: zod_1.z.string().optional().default('-'),
    tempatLahirIbu: zod_1.z.string().optional().default('-'),
    tanggalLahirAyah: zod_1.z.string().optional(),
    tanggalLahirIbu: zod_1.z.string().optional(),
    alamat: zod_1.z.string().min(1),
    desa: zod_1.z.string().optional().default('-'),
    kecamatan: zod_1.z.string().optional().default('-'),
    kabupaten: zod_1.z.string().optional().default('-'),
    provinsi: zod_1.z.string().optional().default('-'),
    kodePos: zod_1.z.string().optional().default('-'),
    noHp: zod_1.z.string().min(1),
    email: zod_1.z.string().email().optional().or(zod_1.z.literal('')),
    asalSekolah: zod_1.z.string().min(1),
    npsnSekolah: zod_1.z.string().optional().default('-'),
    kelasTerakhir: zod_1.z.string().min(1),
    tahunLulus: zod_1.z.string().optional().default('-'),
    noIjazah: zod_1.z.string().optional().default('-'),
    fotoSantri: zod_1.z.string().optional(),
    fotoKtp: zod_1.z.string().optional(),
    fotoAkta: zod_1.z.string().optional(),
    fotoIjazah: zod_1.z.string().optional(),
    fotoKk: zod_1.z.string().optional(),
    suratSehat: zod_1.z.string().optional(),
    fotoSantriApproved: zod_1.z.boolean().optional(),
    fotoKtpApproved: zod_1.z.boolean().optional(),
    fotoAktaApproved: zod_1.z.boolean().optional(),
    fotoIjazahApproved: zod_1.z.boolean().optional(),
    fotoKkApproved: zod_1.z.boolean().optional(),
    suratSehatApproved: zod_1.z.boolean().optional(),
    status: zod_1.z.enum(['pending', 'verified', 'accepted', 'rejected']).optional(),
    catatan: zod_1.z.string().optional(),
});
